server:
  port: 8090

spring:
    datasource:
      url: jdbc:mysql://47.93.53.99:3306/WorkOrder?useUnicode=true&characterEncoding=UTF-8&
            zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 980428
    mail:
      host: smtp.qq.com
      username: 963639898@qq.com
      password: jtaydasthxeebdga
      properties:
        smtp:
          auth: true
          mail.ssl.enable: true
          starttls.enable: true
          starttls.required: true
        debug: true
      protocol: smtp



mybatis:
  config-location: classpath:META-INF/mybatis/mybatis-config.xml
  mapper-locations: classpath:META-INF/mybatis/mapper/*.xml


#logging:
#  level:
#    root: debug
#spring.mail.properties.smtp.auth: true
#spring.mail.properties.smtp.starttls.enable: true
#spring.mail.properties.smtp.starttls.required: true
#spring.mail.properties.mail.smtp.ssl.enable: true